const allProducts = [
  {
    id: 1,
    name: "Vintage Leather Jacket",
    seller: "Nairobi Vintage Co.",
    price: 4500,
    images: [
      "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=600&h=600&fit=crop",
    ],
    rating: 4.8,
    reviews: 124,
    category: "Fashion",
    description:
      "A timeless vintage leather jacket in excellent condition. Perfect for adding a classic edge to any outfit. Features genuine leather construction with a warm, rich patina that only comes with age.",
    inStock: true,
    onSale: false,
    bestseller: true,
  },
  {
    id: 2,
    name: "Classic Record Player",
    seller: "Retro Electronics Hub",
    price: 6200,
    images: [
      "https://images.unsplash.com/photo-1593078165899-67f4e0319bf0?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=600&fit=crop",
    ],
    rating: 4.9,
    reviews: 89,
    category: "Electronics",
    description:
      "Fully functional vintage record player with stunning aesthetic appeal. Plays 33, 45, and 78 RPM records. Recently serviced and tested.",
    inStock: true,
    onSale: false,
  },
  {
    id: 3,
    name: "Ceramic Vase Set",
    seller: "Artisan Home Decor",
    price: 2800,
    images: [
      "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=600&h=600&fit=crop",
    ],
    rating: 4.7,
    reviews: 56,
    category: "Home & Living",
    description:
      "Beautiful set of three handcrafted ceramic vases. Each piece is unique with its own character and glaze variations. Perfect for adding warmth to any interior.",
    inStock: true,
    onSale: true,
    originalPrice: 4200,
    discount: "33%",
  },
  {
    id: 4,
    name: "Vintage Typewriter",
    seller: "Classic Collectibles",
    price: 3900,
    images: [
      "https://images.unsplash.com/photo-1518893883800-45cd0954574b?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1587829191301-4e8dbc4b5f79?w=600&h=600&fit=crop",
    ],
    rating: 4.9,
    reviews: 102,
    category: "Electronics",
    description:
      "Iconic vintage typewriter in working condition. A perfect addition to any writer's desk or collector's shelf. Comes with original ribbon.",
    inStock: true,
    onSale: false,
    bestseller: true,
  },
  {
    id: 5,
    name: "Retro Camera",
    seller: "Photography Vintage",
    price: 5100,
    images: [
      "https://images.unsplash.com/photo-1495707902641-75cac588d2e9?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1606986628025-35d57e735ae0?w=600&h=600&fit=crop",
    ],
    rating: 4.6,
    reviews: 78,
    category: "Electronics",
    description:
      "Beautiful vintage camera with excellent optics. Fully functional and ready to shoot. A must-have for film photography enthusiasts.",
    inStock: true,
    onSale: true,
    originalPrice: 7200,
    discount: "29%",
  },
  {
    id: 6,
    name: "Vintage Pocket Watch",
    seller: "Time Keepers",
    price: 2200,
    images: [
      "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop",
    ],
    rating: 4.8,
    reviews: 145,
    category: "Accessories",
    description:
      "Elegant pocket watch with intricate detailing. Keeps accurate time and is a beautiful conversation piece. Comes with original chain.",
    inStock: true,
    onSale: false,
  },
  {
    id: 7,
    name: "Antique Brass Lamp",
    seller: "Vintage Lighting",
    price: 3400,
    images: [
      "https://images.unsplash.com/photo-1565636192335-14c46fa1120d?w=600&h=600&fit=crop",
    ],
    rating: 4.7,
    reviews: 92,
    category: "Home & Living",
    description:
      "Exquisite antique brass lamp that adds a touch of classic sophistication to any room. Recently rewired for safety.",
    inStock: true,
    onSale: false,
  },
  {
    id: 8,
    name: "Retro Telephone",
    seller: "Nostalgic Tech",
    price: 1800,
    images: [
      "https://images.unsplash.com/photo-1543341724-c6f06da42c4d?w=600&h=600&fit=crop",
    ],
    rating: 4.9,
    reviews: 67,
    category: "Electronics",
    description:
      "Classic rotary telephone in a vibrant vintage hue. A perfect decorative piece that brings back the charm of the 70s.",
    inStock: true,
    onSale: true,
    originalPrice: 2900,
    discount: "38%",
  },
  {
    id: 9,
    name: "Designer Sunglasses",
    seller: "Luxury Vintage",
    price: 3200,
    images: [
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop",
    ],
    rating: 4.8,
    reviews: 98,
    category: "Accessories",
    description:
      "Elegant designer sunglasses from a bygone era. Perfect for adding a touch of luxury to your style.",
    inStock: true,
    onSale: true,
    originalPrice: 5800,
    discount: "45%",
  },
  {
    id: 10,
    name: "Silk Scarf Collection",
    seller: "Heritage Textiles",
    price: 1500,
    images: [
      "https://images.unsplash.com/photo-1601244005535-a48d21d951ac?w=600&h=600&fit=crop",
    ],
    rating: 4.6,
    reviews: 64,
    category: "Fashion",
    description:
      "Beautiful silk scarf with intricate patterns. Hand-rolled edges and vibrant colors.",
    inStock: true,
    onSale: false,
  },
  {
    id: 11,
    name: "Vintage Watch",
    seller: "Time Keepers",
    price: 2800,
    images: [
      "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&h=600&fit=crop",
    ],
    rating: 4.9,
    reviews: 156,
    category: "Accessories",
    description:
      "A classic timepiece that never goes out of style. Precision movement and elegant design.",
    inStock: true,
    onSale: false,
    bestseller: true,
  },
  {
    id: 12,
    name: "Leather Crossbody Bag",
    seller: "Artisan Leather",
    price: 2100,
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop",
    ],
    rating: 4.7,
    reviews: 112,
    category: "Fashion",
    description:
      "Durable and stylish leather crossbody bag. Perfect for everyday use with multiple compartments.",
    inStock: true,
    onSale: true,
    originalPrice: 4200,
    discount: "50%",
  },
];

export { allProducts };
